# Generated by Django 2.2.20 on 2022-01-09 17:24

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.FloatField()),
                ('const_nam', models.CharField(max_length=50)),
                ('const_no', models.FloatField()),
                ('county_nam', models.CharField(max_length=50)),
                ('st_area_sh', models.FloatField()),
                ('st_length_field', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('globalid', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
            },
        ),
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('fruits', models.IntegerField()),
                ('weight', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidences',
            fields=[
                ('incidnce_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='user@user.com', max_length=100)),
                ('phonenumber', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='phone number is in the format 0703111222, up to 10 digits allowed', regex='^\\+?1?\\d{13,15}$')])),
                ('incidence_date', models.DateTimeField(auto_now_add=True)),
                ('incidence_type', models.CharField(choices=[('Pests', 'Pests'), ('Diseases', 'Diseases'), ('Natural occurences', 'Natural occurences'), ('Corning', 'Corning'), ('Other', 'Other')], max_length=50)),
                ('incidence_description', models.TextField(max_length=200)),
                ('nearest_town', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(null=True, upload_to='reports')),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Still Open', 'Still Open'), ('UnSolved', 'UnSolved')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Reported Incidences',
            },
        ),
        migrations.CreateModel(
            name='PickupSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, verbose_name='Route Name')),
                ('stakeholder', models.CharField(choices=[('Exporters', 'Exporters'), ('Supplier', 'Suppliers'), ('Company', 'Company'), ('Broker', 'Broker')], max_length=30)),
                ('departure', models.DateTimeField(verbose_name='Departure')),
                ('stops', models.CharField(max_length=300, verbose_name='Stop Locations')),
                ('source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PruningCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seedlings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cultivar', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='cultivars')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='phone number is in the format 0703111222, up to 10 digits allowed', regex='^\\+?1?\\d{13,15}$')])),
                ('dealer', models.CharField(choices=[('Exporters', 'Exporters'), ('Supplier', 'Suppliers'), ('Company', 'Company'), ('Broker', 'Broker')], max_length=50)),
                ('physical_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telnumber', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('photo', models.ImageField(upload_to='', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
