# Generated by Django 2.2.20 on 2022-01-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidences',
            name='photo',
        ),
    ]
