# Generated by Django 2.2.20 on 2022-01-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_remove_incidences_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestdetails',
            name='date',
            field=models.DateField(),
        ),
    ]
