# Generated by Django 2.2.20 on 2022-01-21 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geoapp', '0004_auto_20220119_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidences',
            old_name='incidnce_id',
            new_name='incidence_id',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='last_name',
        ),
        migrations.AddField(
            model_name='incidences',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidences',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
