# Generated by Django 2.2.20 on 2022-01-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0005_auto_20220121_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
