# Generated by Django 2.2.20 on 2022-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0006_auto_20220121_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
